### PR TITLE
Updates signing key used for directory

### PR DESCRIPTION
**Pull request by conorsch**
We're using _my_ key for the directory trust, since FPFers have it already. Since I'm in the middle of a key transition (:tada:), we should probably use the _new_ key—but I'd rather use the old key to deliver the new one, frankly. 

In the near future we can amend the signature to use only one public key. At present, the fingerprint list is dual-signed—so either of the following fingerprints can be used for verification:

  * `BA6D6CCD31048CF8D68730EB5E77E0FEF9A1A94D`
  * `0B095DF428491E147B615CD3F08893B959CAB065`

Also tacked on a helper script since I know I'll need it later. 🤠

### CODE REVIEW

**Comment by conorsch** [comment]
Shucks, looks like gpgsync doesn't support dual-signing. Confirmed that with @micahflee. Revising....

**Comment by conorsch** [comment]
Updated, ready for review.

**Comment by msheiny** [comment]
> Shucks, looks like gpgsync doesn't support dual-signing. Confirmed that with @micahflee. Revising....

I mean.. its open-source, we could submit a PR to add dual-signing support. Though - I'm fine with pivoting to an FPF infra specific shared key.

**Comment by conorsch** [comment]
Thanks for quick review, @emkll. Going to close this PR and re-implement with a dedicated key.

**Pull request closed without merging**
